spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/weixin?characterEncoding=utf8&useSSL=false
  redis:
    host: 127.0.0.1
#  jpa:
#    show-sql: true
  devtools:
    restart:
      enabled: true #设置开启热部署
      # additional-paths: src/main/java #重启目录
      # exclude: WEB-INF/**
  freemarker:
    cache: false  #页面不加载缓存，修改即时生效
#  jackson:
#    default-property-inclusion: non_null
server:
  context-path: /sell

resources: # 指定静态资源的路径
  static-locations: classpath:/static/,classpath:/views/
  cache-period: 0

# 公众号配置(用户支付)
wechat:
  mpAppId: wxd898fcb01713c658
  mpAppSecret: 47ccc303338cee6e62894fxxxxxxxxxxx
  openAppId: wx6ad144e54af67d87
  openAppSecret: 91a2ff6d38a2bbccfb7e9f9079108e2e
  mchId: 1483469312
  mchKey: 06C56A89949D617xxxxxxxxxxx
  keyPath: /var/weixin_cert/h5.p12
  notifyUrl: http://sell.natapp4.cc/sell/pay/notify
  templateId:
    orderStatus: e-Cqq67QxD6YNI41iRiqawEYdFavW_7pc7LyEMb-yeQ

# 微信开放平台配置(用户微信扫码登录)
wechatOpen:
  mpAppId: wxd898fcb01713c658
  mpAppSecret: 47ccc303338cee6e62894fxxxxxxxxxxx
  openAppId: wx6ad144e54af67d87
  openAppSecret: 91a2ff6d38a2bbccfb7e9f9079108e2e
  mchId: 1483469312
  mchKey: 06C56A89949D617xxxxxxxxxxx
  keyPath: /var/weixin_cert/h5.p12
  notifyUrl: http://sell.natapp4.cc/sell/pay/notify
  templateId:
    orderStatus: e-Cqq67QxD6YNI41iRiqawEYdFavW_7pc7LyEMb-yeQ


projectUrl:
  wechatMpAuthorize: http://sell.natapp4.cc # 微信公众平台授权url(用于微信支付)
  wechatOpenAuthorize: http://sell.natapp4.cc # 微信开放平台授权url（用于微信扫码登录）
  sell: http://sell.natapp4.cc # 微信公众平台授权url（项目地址）
